### ISSUE TITLE
Some objects are not consistently assigned IDs in IE<=10

### ISSUE THREAD

**Issue by mdittmer** [mdittmer/id-js#2]
- `defineProperty()` will sometimes silently fail in IE (version <= 10)
- `__proto__` was standardized in ES6, and not available in IE (version <= 10)

These results is failure to assign an ID to some objects.

**Comment by jingt06** [comment]
This issue also exists in IE 11, results failure to assign unique IDs to objects' prototype.

**Comment by mdittmer** [comment]
In particular, Object.prototype and other things, such as Window.prototype
wind up with the same ID in object-graph-js. Object.prototype !=
Window.prototype.

**Comment by mdittmer** [comment]
@jingt06 did we end up fixing this, or is it an outstanding issue?

**Comment by jingt06** [comment]
This issue should be fixed by the previous commit, where we added getPariedId when uid value was not changed. https://github.com/mdittmer/id-js/blob/master/id.js#L75

**Comment by mdittmer** [comment]
Fixed in 8b36a89bff3aca8506257eb2af51692b284871d9
